# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Maven wrapper and project files
COPY . .

# Package the app
RUN ./mvnw clean install -DskipTests

# Run the Spring Boot app
CMD ["java", "-jar", "target/cinemabs-0.0.1-SNAPSHOT.jar"]
