FROM maven:3.9.6-eclipse-temurin-17 AS builder

WORKDIR /app

COPY . .

RUN chmod +x mvnw && ./mvnw clean install -DskipTests

# Use a smaller JDK runtime for the final image
FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy only the JAR from the builder image
COPY --from=builder /app/target/cinemabs-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

# Run the Spring Boot app
CMD ["java", "-jar", "app.jar"]
